{{- if eq .Values.cloudprovider "openstack" }}
{{- range $index, $nodepool := .Values.nodepools }}
---
# OpenStack configuration (ref. openstackconfigs.rke-machine-config.cattle.io CRD)
apiVersion: rke-machine-config.cattle.io/v1
kind: OpenstackConfig
metadata:
  name: {{ $nodepool.name }}
  namespace: fleet-default
  # annotations:
  #   key: string
{{- if $nodepool.labels }}
  labels:
{{ toYaml $nodepool.labels | indent 4 }}
{{- end }}
activeTimeout: "{{ default "200" $nodepool.activeTimeout }}"
applicationCredentialId: "{{ default "" $nodepool.applicationCredentialId }}"
applicationCredentialName: "{{ default "" $nodepool.applicationCredentialName }}"
applicationCredentialSecret: "{{ default "" $nodepool.applicationCredentialSecret }}"
authUrl: {{ $nodepool.authUrl | quote }}
availabilityZone: {{ coalesce $nodepool.availabilityZone $.Values.openstack.availabilityZone "nova" }}
bootFromVolume: {{ default "false" $nodepool.bootFromVolume }}
cacert: "{{ default "" $nodepool.cacert }}"
configDrive: {{ default "false" $nodepool.configDrive }}
domainId: "{{ default "" $nodepool.domainId }}"
{{- if or $nodepool.domainName $.Values.openstack.domainName }}
domainName: {{ coalesce $nodepool.domainName $.Values.openstack.domainName }}
{{- end }}
endpointType: {{ default "publicURL" $nodepool.endpointType }}
flavorId: "{{ default "" $nodepool.flavorId }}"
{{- if or $nodepool.flavorName $.Values.openstack.flavorName }}
flavorName: {{ coalesce $nodepool.flavorName $.Values.openstack.flavorName | quote }}
{{- end }}
floatingipPool: "{{ default "" $nodepool.floatingipPool }}"
imageId: "{{ default "" $nodepool.imageId }}"
{{- if or $nodepool.imageName $.Values.openstack.imageName }}
imageName: {{ coalesce $nodepool.imageName $.Values.openstack.imageName | quote }}
{{- end }}
insecure: {{ default "false" $nodepool.insecure }}
ipVersion: "{{ default "4" $nodepool.ipVersion }}"
keypairName: {{ coalesce $nodepool.keypairName $.Values.openstack.keypairName }}
netId: "{{ default "" $nodepool.netId }}"
{{- if or $nodepool.netName $.Values.openstack.netName }}
netName: {{ coalesce $nodepool.netName $.Values.openstack.netName }}
{{- end }}
novaNetwork: {{ default "false" $nodepool.novaNetwork }}
password: "{{ default "" $nodepool.password }}"
privateKeyFile: |
{{ coalesce $nodepool.privateKeyFile $.Values.openstack.privateKeyFile | indent 2 }}
region: {{ coalesce $nodepool.region $.Values.openstack.region "RegionOne" }}
sshPort: {{ coalesce $nodepool.sshPort "22" | quote }}
sshUser: {{ coalesce $nodepool.sshUser $.Values.openstack.sshUser "ubuntu"}}
secGroups: {{ coalesce $nodepool.secGroups $.Values.openstack.secGroups "default"}}
tenantDomainId: "{{ default "" $nodepool.tenantDomainId }}"
tenantDomainName: "{{ default "" $nodepool.tenantDomainName }}"
tenantId: "{{ default "" $nodepool.tenantId }}"
{{- if or $nodepool.tenantName $.Values.openstack.tenantName }}
tenantName: {{ coalesce $nodepool.tenantName $.Values.openstack.tenantName }}
{{- end }}
{{- if or $nodepool.userDataFile $.Values.openstack.userDataFile }}
userDataFile: |
{{- coalesce $nodepool.userDataFile $.Values.openstack.userDataFile | nindent 2 }}
{{- end }}
userDomainId: "{{ default "" $nodepool.userDomainId }}"
userDomainName: "{{ default "" $nodepool.userDomainName }}"
userId: "{{ default "" $nodepool.userId }}"
{{- if or $nodepool.username $.Values.openstack.username }}
username: {{ coalesce $nodepool.username $.Values.openstack.username "admin" }}
{{- end }}
volumeDevicePath: "{{ default "" $nodepool.volumeDevicePath }}"
volumeId: "{{ default "" $nodepool.volumeId }}"
volumeName: "{{ default "" $nodepool.volumeName }}"
volumeSize: "{{ default "" $nodepool.volumeSize }}"
volumeType: "{{ default "" $nodepool.volumeType }}"
{{- end }}
{{- end }}
