apiVersion: v1
name: openstack-cluster-template
description: Cluster templates for rke2 with openstack
version: 0.0.1
annotations:
  catalog.cattle.io/type: cluster-template
  catalog.cattle.io/namespace: fleet-default
