openstack:
  sshUser: ubuntu
  sshPort: 22
  secGroups: default
  region: RegionOne
  domainName: Default
  availabilityZone: nova
  userDataFile: |
    #cloud-config
    password: openstack
    chpasswd: { expire: False }
    ssh_pwauth: True
nodepools:
  - etcd: true
    controlplane: true
    worker: false
    labels: {}
    quantity: 1
    name: master
  - etcd: false
    controlplane: false
    worker: true
    labels: {}
    quantity: 1
    name: worker